name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@2021-A
        with:
          # The root LaTeX file to be compiled
          root_file: 00_main.tex
          compiler: xelatex
          #extra_system_packages: true
      - name: Upload a build artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          path: .
